
" Check if vim-plug is already installed, if not, install
"   If behind HTTP proxy, you may need to add --insecure option to the curl command.
"   You may also need to set $GIT_SSL_NO_VERIFY to true. 
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall | source $MYVIMRC
        endif

set nocompatible              " be iMproved, required
"filetype off                  " not required with vimplug

"------------------->>> VIM-PLUG <<< ---------------"
" Brief help
"  PlugInstall [name ...] [#threads]  - Install plugins
"  PlugUpdate [name ...] [#threads]   - Install or update plugins
"  PlugClean[!]                       - Remove unused directories (bang version will clean without prompt)
"  PlugUpgrade                        - Upgrade vim-plug itself
"  PlugStatus                         - Check the status of plugins


    call plug#begin('~/.vim/plugs')

        " My Plugins
        Plug 'tpope/vim-fugitive'
        Plug 'tpope/vim-sensible'
        Plug 'tpope/vim-surround'

        Plug 'bling/vim-bufferline'
        Plug 'bitc/vim-bad-whitespace'
        Plug 'easymotion/vim-easymotion'
        Plug 'kien/ctrlp.vim'
        Plug 'scrooloose/syntastic'
        Plug 'scrooloose/nerdtree'

        Plug 'benmills/vimux'
        Plug 'christoomey/vim-tmux-navigator'
        Plug 'edkolev/tmuxline.vim'
        Plug 'tmux-plugins/vim-tmux'
        Plug 'tmux-plugins/vim-tmux-focus-events'

        Plug 'sheerun/vim-polyglot'
        "Plug 'othree/yajs.vim`, { 'for': 'javascript' }
        "Plug 'gavocanov/vim-js-indent', { 'for': 'javascript' }

        "Themes
        Plug 'vim-airline/vim-airline'
        Plug 'vim-airline/vim-airline-themes'
        Plug 'chriskempson/base16-vim'
        "Plugin 'nanotech/jellybeans.vim'

        "Javascript
   "Plugin 'Valloric/YouCompleteMe'
   "Plugin 'marijnh/tern_for_vim'
   "Plugin 'jelera/vim-javascript-syntax'
    "Plugin 'vim-scripts/JavaScript-Indent'

        " All of your Plugins must be added before the following line
        call plug#end()            " required
"------------------->>> NON-VIM-PLUG BELOW HERE <<< ---------------"

let mapleader=","                   " , is the control/meta/leader character
"color jellybeans
let base16colorspace=256
"colorscheme base16-default
set background=dark

set modelines=0
set title                           " Set Window title
set tabstop=2                       " Set up tabs so that they insert 4 spaces instead of a tab character
set shiftwidth=2
set softtabstop=2
set expandtab

set paste                           " Use intelligent paste with whitespace

set foldmethod=indent
set foldlevel=99

set t_Co=256
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden                          "turn on buffers to manage memory
set wildmenu                        "tab gives more command possibilities
set wildmode=list:longest
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set number

nnoremap / /\v
vnoremap / /\v
set ignorecase                      "ignores case in searching
set smartcase                       "case sensitive for capital letters when searching
set gdefault
set showmatch
set hlsearch                        "Highlight search terms...
set incsearch                       "...dynamically as they are typed.
hi Search ctermbg=LightBlue
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set scrolloff=3

au FocusLost * :wa                  "save austomatically when focus is lost
highlight Pmenu ctermbg=blue        "Change menu color to something nicer looking

set list                            "Show whitespace and whitespace characters
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

nnoremap <up> <nop>                 "Get rid of arrow keys when in command mode; learn HJKL!
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

nnoremap j gj
nnoremap k gk
nnoremap ' `
nnoremap ` '

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap <leader>w <C-w>v<C-w>1
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

"------------------->>> TMUXLINE <<< ---------------"
" Disable separators
let g:tmuxline_powerline_separators = 0

" Status line is minimal and looks like this:
"   | session > 1. Win name > ... < CPU Usage |
"let g:tmuxline_preset = {
"  \'a'    : '#S',
"  \'win'  : '#I:#W',
"  \'cwin' : '#I:#W',
"  \'options': {
"    \'status-justify': 'left'
"    \}
"  \}

let g:tmuxline_preset = 'nightly_fox'

"------------------->>> AIRLINE <<< ---------------"
" Set an Airline Theme
let g:airline_theme="bubblegum"
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
" Populate g:airline_symbols dict with powerline symbols
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

"------------------->>> CTRL+P <<< ---------------"
" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
  \}

" Use the nearest .git directory as the cwd
let g:ctrlp_working_path_mode = 'r'

" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>

" Easy bindings for its various modes
nmap <leader>bb :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>

"------------------->>> VIMUX <<< ---------------"
"    From www.braintreepayments.com/blog/vimux-simple-vim-and-tmux-integration/

 " Prompt for a command to run
 map <Leader>vp :VimuxPromptCommand<CR>
 " Run last command executed by VimuxRunCommand
 map <Leader>vl :VimuxRunLastCommand<CR>
 " Inspect runner pane
 map <Leader>vi :VimuxInspectRunner<CR>
 " Close vim tmux runner opened by VimuxRunCommand
 map <Leader>vq :VimuxCloseRunner<CR>
 " Interrupt any command running in the runner pane
 map <Leader>vx :VimuxInterruptRunner<CR>
 " Zoom the runner pane (use <bind-key> z to restore runner pane)
 map <Leader>vz :call VimuxZoomRunner()<CR>


"------------------->>> WINDOW MANAGEMENT <<< ---------------"
"		From http://www.agillo.net/simple-vim-window-management/
set title

function! WinMove(key)
    let t:curwin = winnr()
    exec "wincmd ".a:key
    if (t:curwin == winnr()) "we havent moved
        if (match(a:key,'[jk]')) "were we going up/down
            wincmd v
        else
            wincmd s
        endif
        exec "wincmd ".a:key
    endif
endfunction

map <leader>h              :call WinMove('h')<cr>
map <leader>k              :call WinMove('k')<cr>
map <leader>l              :call WinMove('l')<cr>
map <leader>j              :call WinMove('j')<cr>
map <leader>wc :wincmd q<cr>
map <leader>wr <C-W>r
